baseURL = "http://slides.agilebuckle.com"
languageCode = "en-us"
title = "Slides"
theme = "reveal-hugo"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

relativeURLs = true
uglyURLs = true
canonifyURLs = false

